/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import Config.DbConfig;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Validasi extends javax.swing.JFrame {
    Connection conn = DbConfig.getConnection();
    Integer id = null;
    DefaultTableModel tabmodel;
    DefaultComboBoxModel combomodel;
    Integer selected = null;
    String tablename = "pemesanan";
    String text = "Cekin";
    ArrayList<Integer> arrayid = null;
    
    
    public void judul() {
        String[] judul = {
          "ID","Kode Pemesanan","Tanggal Pemesanan","Tempat Pemesanan","Pelanggan","Kode Kursi","Tujuan","Rute","Harga","Tanggal Berangkat","Jam Cekin","Jam Berangkat","Petugas"  
        };
        tabmodel = new DefaultTableModel(null,judul);
        table_typetransportasi.setModel(tabmodel);
    }
    
    
    
    public void showData(String s) {
        tabmodel.getDataVector().removeAllElements();
        tabmodel.fireTableDataChanged();
        try {
            String search = "";
            if (!s.isEmpty() && s!=null) {
                search = " WHERE kode_pemesanan LIKE '%"+s+"%'";
            }
            ResultSet resu = conn.createStatement().executeQuery("SELECT * FROM "+tablename+search);
            while (resu.next()) {
                String tujuan = null;
                String awal = null;
                String ahir = null;
//                String.format("%,d",resu.getInt("harga"))
                Integer harga = null;
                String pelanggan = null;
                String petugas = "";
                ResultSet res1 = conn.createStatement().executeQuery("SELECT tujuan,rute_awal,rute_ahir,harga FROM rute WHERE id_rute="+resu.getString("id_rute"));
                if (res1.next()) {
                    tujuan = res1.getString("tujuan");
                    awal = res1.getString("rute_awal");
                    ahir = res1.getString("rute_ahir");
                    harga = res1.getInt("harga");
                }
                ResultSet res2 = conn.createStatement().executeQuery("SELECT nama_penumpang FROM penumpang WHERE id_penumpang="+resu.getString("id_pelanggan"));
                if (res2.next()) {
                    pelanggan = res2.getString("nama_penumpang");
                }
                ResultSet res3 = conn.createStatement().executeQuery("SELECT nama_petugas FROM petugas WHERE id_petugas="+resu.getString("id_petugas"));
                if (res3.next()) {
                    petugas = res3.getString("nama_petugas");
                }
                Object[] data = {
                    resu.getInt("id_pemesanan"),
                    resu.getString("kode_pemesanan"),
                    resu.getString("tanggal_pemesanan"),
                    resu.getString("tempat_pemesanan"),
                    pelanggan,
                    resu.getString("kode_kursi"),
                    tujuan,
                    awal+" - "+ahir,
                    String.format("%,d",harga),
                    resu.getString("tanggal_berangkat"),
                    resu.getString("jam_cekin").substring(0, 5),
                    resu.getString("jam_berangkat").substring(0, 5),
                    petugas
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void enableButton(Boolean a) {
        if (a==true) {
            btn_Update.setText(text+" ("+selected+")");
        } else if (a==false) {
            btn_Update.setText(text);
        }
        btn_Update.setEnabled(a);
    }
    
    
    
    /**
     * Creates new form CRUDpenumpang
     */
    public Validasi(Integer uid) {
        initComponents();
        judul();
        if (uid!=null) {
            id = uid;
            try {
                String query = "SELECT nama_petugas FROM petugas WHERE id_petugas="+id;
                ResultSet resu = conn.createStatement().executeQuery(query);
                if (resu.next()) {
                    txt_nama.setText(resu.getString("nama_petugas"));
                }
            } catch (Exception e) {
                
            }
        }
        showData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_typetransportasi = new javax.swing.JTable();
        txt_nama = new javax.swing.JLabel();
        btn_Update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_typetransportasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_typetransportasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_typetransportasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_typetransportasi);

        txt_nama.setText("User");

        btn_Update.setText("Cekin");
        btn_Update.setEnabled(false);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        jLabel4.setText("Kode");

        txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nama)
                            .addComponent(btn_Update))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_typetransportasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_typetransportasiMouseClicked
        // TODO add your handling code here:
        try {
            Integer currentid = Integer.parseInt(table_typetransportasi.getValueAt(table_typetransportasi.getSelectedRow(), 0).toString());
            ResultSet resu = conn.createStatement().executeQuery("SELECT id_petugas FROM pemesanan WHERE id_pemesanan="+currentid);
            if (resu.next()) {
                if (resu.getObject("id_petugas")==null) {
                    selected = currentid;
                    enableButton(true);
                } else {
                    enableButton(false);
                }
            }
            
//            if (resu.next()) {
//                selected=resu.getInt("id_transportasi");
//                txt_kode.setText(resu.getString("kode"));
//                txt_jumlahkursi.setText(resu.getString("jumlah_kursi"));
//                txt_keterangan.setText(resu.getString("keterangan"));
//                combo_typetransportasi.setSelectedIndex(arrayid.indexOf(resu.getInt("id_type_transportasi"))+1);
//                enableButton(true);
//            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_table_typetransportasiMouseClicked

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        if (id!=null && selected!=null) {
        try {
            String query = "UPDATE "+tablename+" SET id_petugas="+id+" WHERE id_pemesanan="+selected;
            Integer updated = conn.createStatement().executeUpdate(query);
            
                if (updated>0) {
                    JOptionPane.showMessageDialog(this, "Cekin berhasil");
                }
            showData("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeActionPerformed
        // TODO add your handling code here:
        showData(txt_kode.getText());
    }//GEN-LAST:event_txt_kodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validasi(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_typetransportasi;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JLabel txt_nama;
    // End of variables declaration//GEN-END:variables
}
